### test farmer signup
POST http://localhost:8080/api/auth/farmer/signup
Content-Type: application/json

{
	"name": "Ram",
	"password": "password",
	"mobile": "9090909090",
	"address": "221B, Baker Street, London"
}

### test farmer login
POST http://localhost:8080/api/auth/farmer/login
Content-Type: application/json

{
	"password": "password",
	"mobile": "9090909090"
}

### test buyer signup
POST http://localhost:8080/api/auth/buyer/signup
Content-Type: application/json

{
	"name": "Laxman",
	"password": "password",
	"mobile": "9090909091",
	"address": "221B, Baker Street, New Delhi"
}

### test buyer login
POST http://localhost:8080/api/auth/buyer/login
Content-Type: application/json

{
	"password": "password",
	"mobile": "9090909091"
}

### add listing
POST http://localhost:8080/api/listing
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtb2JpbGUiOiI5MDkwOTA5MDkwIiwiaWQiOiI1ZTQ1MjZiZjBjZTg2NzI2MWVmZTUzOWEiLCJpYXQiOjE1ODE1OTMyODUsImV4cCI6MTU4MjE5ODA4NX0.y5CrL2G6iUe76hRK959cahbtn5OqBcjFdOSRYddMc9o

{
	"name": "Wheat",
	"price": 123,
	"image": "/upload/luvb.jpg"
}